### ISSUE TITLE
增加国际服支持

### ISSUE THREAD

**Issue by win98se** [GamerNoTitle/MHYY#25]
https://github.com/Linsent20/GenshinCloud-AutoCheckIn/issues/2

国际服也有云·原神了，想问是否有打算增加对其的支持

**Comment by GamerNoTitle** [comment]
发个云原国际的链接我去看看 不过我还得从新手开始就是了

**Comment by GamerNoTitle** [comment]
@win98se 明天看看 应该差不多

**Comment by GamerNoTitle** [comment]
刚推了一个commit，你可以试试，抓包方式没变

**Comment by GamerNoTitle** [comment]
```yaml
  - token:
    # 关于type：如果你在安卓版的云·原神里面抓的话type应该是2
    # 如果你是网页版抓的，那type应该是16
    # 此处仅供参考，具体以你抓的为准 
    type: 
    # sysver：如果你是安卓版抓的，这个应该会显示你的安卓版本（鸿蒙不清楚，手上没设备）
    # 如果你是网页版抓的，这个应该是你的系统版本（注：Windows 10和Windows 11都是写的Windows 10）
    sysver: 
    # deviceid：手机抓的会有这个，抓到什么填什么
    # 如果是网页版抓的，那也是抓到什么填什么
    deviceid: 
    # devicename: 手机抓的话就是手机的入网型号，如红米K40为M2012K11AC，红米K50为22021211RC
    # 如果是网页版抓的，填Unknown
    devicename: 
    # devicemodel: 手机抓的填抓出来的手机型号，大概为手机厂商+上面的deviceid，如红米K40为Xiaomi M2012K11AC
    # 如果是网页版抓的，填Unknown
    devicemodel: 
    # appid: 国服手机抓的固定填1953439974，网页版抓的留空；国际服手机抓的填9000254
    appid: 
    # region(可选): 账号所处的地区，国服填cn，国际服填os，不填或非法值按国服处理
    region: os
```
国际服账号要加多一个`region: os`

**Comment by GamerNoTitle** [comment]
我测试很不稳定 我这边经常被CloudFront拦下来

**Comment by GamerNoTitle** [comment]
我测试很不稳定 我这边经常被CloudFront拦下来

**Comment by win98se** [comment]
根据文档，“`appid`是（请求）里面的`x-rpc-app_id`”，我这里的`x-rpc-app_id`抓到是600493，而不是9000254
（不过我看到一个类似的，`x-rpc-cg_game_id`是9000156）

我刚刚配置了以以下配置运行，坐等第一个结果
```
accounts:
  - token: ai=4;ci=1;oi=bbs_id;ct=ct_token;si=si_token;bi=hk4e_global
    type: 2
    sysver: 9
    deviceid: 9854468c-933b-3d9e-8bae-c3ff182659b7
    devicename: TCL 5048I
    devicemodel: 5048I
    appid: 600493
    region: os
```

**Comment by win98se** [comment]
根据文档，“`appid`是（请求）里面的`x-rpc-app_id`”，我这里的`x-rpc-app_id`抓到是600493，而不是9000254
（不过我看到一个类似的，`x-rpc-cg_game_id`是9000156）

我刚刚配置了以以下配置运行，坐等第一个结果
```
accounts:
  - token: ai=4;ci=1;oi=bbs_id;ct=ct_token;si=si_token;bi=hk4e_global
    type: 2
    sysver: 9
    deviceid: device_uuid
    devicename: TCL 5048I
    devicemodel: 5048I
    appid: 600493
    region: os
```
